CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(254) NOT NULL UNIQUE,
 name VARCHAR(150) NOT NULL,
 password_hash VARCHAR(200) NOT NULL,
 role ENUM('erp','vendor','customer') NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 expires_at DATETIME NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX(expires_at)
);
CREATE TABLE IF NOT EXISTS lookup_values (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 field_name VARCHAR(80) NOT NULL,
 label VARCHAR(254) NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 UNIQUE(field_name,label)
);
CREATE TABLE IF NOT EXISTS quotes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 owner_id BIGINT UNSIGNED NOT NULL,
 status VARCHAR(40) NOT NULL DEFAULT 'Draft',
 version INT UNSIGNED NOT NULL DEFAULT 1,
 details JSON NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (owner_id) REFERENCES users(id),
 INDEX(owner_id,status,created_at)
);
CREATE TABLE IF NOT EXISTS audit_log (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 entity VARCHAR(50) NOT NULL,
 entity_id BIGINT UNSIGNED NOT NULL,
 action VARCHAR(50) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS portal_demo_records (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 reference VARCHAR(40) NOT NULL,
 organization VARCHAR(150) NOT NULL,
 route VARCHAR(150) NOT NULL,
 status VARCHAR(40) NOT NULL,
 UNIQUE(user_id,reference),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
