CREATE TABLE IF NOT EXISTS business_records (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 kind VARCHAR(40) NOT NULL,
 owner_id BIGINT UNSIGNED NOT NULL,
 status VARCHAR(50) NOT NULL DEFAULT 'Draft',
 version INT UNSIGNED NOT NULL DEFAULT 1,
 details JSON NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_id) REFERENCES users(id),
 INDEX(kind,owner_id,status), INDEX(updated_at)
);
CREATE TABLE IF NOT EXISTS record_notes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 record_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 visibility ENUM('internal','shared') NOT NULL DEFAULT 'internal',
 message TEXT NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(record_id) REFERENCES business_records(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS record_documents (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 record_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(200) NOT NULL,
 mime VARCHAR(100) NOT NULL,
 content MEDIUMBLOB NOT NULL,
 visibility ENUM('internal','shared') NOT NULL DEFAULT 'internal',
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(record_id) REFERENCES business_records(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS record_payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 record_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 amount DECIMAL(18,2) NOT NULL,
 reference VARCHAR(200) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(record_id) REFERENCES business_records(id),
 FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS ledger_entries (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 record_id BIGINT UNSIGNED NOT NULL,
 account VARCHAR(50) NOT NULL,
 currency CHAR(3) NOT NULL,
 debit DECIMAL(18,2) NOT NULL DEFAULT 0,
 credit DECIMAL(18,2) NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(record_id) REFERENCES business_records(id),
 INDEX(account,currency)
);
CREATE TABLE IF NOT EXISTS record_followers (
 record_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(record_id,user_id),
 FOREIGN KEY(record_id) REFERENCES business_records(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS workspace_notifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 record_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 message VARCHAR(200) NOT NULL,
 is_read BOOLEAN NOT NULL DEFAULT FALSE,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(record_id) REFERENCES business_records(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX(user_id,is_read)
);
CREATE TABLE IF NOT EXISTS workspace_mail (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 record_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 recipient VARCHAR(254) NOT NULL,
 subject VARCHAR(200) NOT NULL,
 message TEXT NOT NULL,
 status ENUM('Queued','Sending','Sent','Failed') NOT NULL DEFAULT 'Queued',
 error VARCHAR(300) NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(record_id) REFERENCES business_records(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id),
 INDEX(user_id,status)
);
